INSERT INTO `caracteristicas` (`nome`) VALUES ('2 quartos 1 banheiro'), 
                                    ('2 quartos 2 banheiros'), 
                                    ('2 quartos 3 banheiros'),  
                                    ('3 quartos 1 banheiro'),
                                    ('3 quartos 2 banheiros'),
                                    ('3 quartos 3 banheiros'), 
                                    ('3 quartos 3 banheiros 1 suite'), 
                                    ('4 quartos 3 banheiros 1 suite'), 
                                    ('2 quartos 1 banheiro com garagem'), 
                                    ('2 quartos 2 banheiros com garagem'), 
                                    ('2 quartos 3 banheiros com garagem'),  
                                    ('3 quartos 1 banheiro com garagem'),
                                    ('3 quartos 2 banheiros com garagem'),
                                    ('3 quartos 3 banheiros com garagem'), 
                                    ('3 quartos 3 banheiros 1 suite com garagem'), 
                                    ('4 quartos 3 banheiros 1 suite com garagem'), 
                                    ('kitnet');